### ISSUE TITLE
Crashed after OAuth2 logged in

### ISSUE THREAD

**Issue by KunNiu** [ciscospark/spark-android-sdk-example#3]
App always crashed about 1 mins after OAuth2 logged in.
log as below:
03-13 17:46:16.212 25779-26801/com.cisco.sparksdk.sparkkitchensink E/AndroidRuntime: FATAL EXCEPTION: Metrics reporter timer (start)
                                                                                     Process: com.cisco.sparksdk.sparkkitchensink, PID: 25779
                                                                                     com.cisco.spark.android.authenticator.NotAuthenticatedException
                                                                                         at com.cisco.spark.android.core.ApiClientProvider.getMetricsClient(ApiClientProvider.java:407)
                                                                                         at com.cisco.spark.android.metrics.MetricsReporter$ReportMetricsTimerTask.run(MetricsReporter.java:217)
                                                                                         at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                                         at java.util.TimerThread.run(Timer.java:505)
03-13 17:46:16.212 25779-26801/com.cisco.sparksdk.sparkkitchensink D/AppTracker: App Event: crash
03-13 17:46:16.213 25779-26786/com.cisco.sparksdk.sparkkitchensink D/RetryPolicy:177: OperationWalker  1520934316202 : Operation attempt started at 1520934376211
03-13 17:46:16.215 25779-26786/com.cisco.sparksdk.sparkkitchensink D/Operation: OperationWalker  Operation 3b78ea97-cc11-427b-a920-4dd53053cf0f POST_GENERIC_METRIC EXECUTING [GenericMetric metricName client_device_registered]  <= READY
03-13 17:46:16.217 25779-26788/com.cisco.sparksdk.sparkkitchensink W/Api: OperationWorker2  Device data reported null metrics service url
03-13 17:46:16.222 25779-26788/com.cisco.sparksdk.sparkkitchensink E/WalkOperationQueueTask:178: OperationWorker2  Operation  3b78ea97-cc11-427b-a920-4dd53053cf0f POST_GENERIC_METRIC EXECUTING [GenericMetric metricName client_device_registered] faulted
                                                                                                 com.cisco.spark.android.authenticator.NotAuthenticatedException
                                                                                                     at com.cisco.spark.android.core.ApiClientProvider.getMetricsClient(ApiClientProvider.java:407)
                                                                                                     at com.cisco.spark.android.sync.operationqueue.PostGenericMetricOperation.postMetrics(PostGenericMetricOperation.java:176)
                                                                                                     at com.cisco.spark.android.sync.operationqueue.PostGenericMetricOperation.doWork(PostGenericMetricOperation.java:138)
                                                                                                     at com.cisco.spark.android.sync.operationqueue.core.WalkOperationQueueTask$OperationWorkTask.call(WalkOperationQueueTask.java:133)
                                                                                                     at com.cisco.spark.android.sync.operationqueue.core.WalkOperationQueueTask$OperationWorkTask.call(WalkOperationQueueTask.java:117)
                                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                     at java.lang.Thread.run(Thread.java:761)

**Comment by xionxiao** [comment]
It seems the device registration failed.
